queue: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:

  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: 3.1.100-preview1-014459

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: src/Blazor.Extensions.Logging.JS

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: 'src/Blazor.Extensions.Logging/*.csproj'
      configuration: '$(buildConfiguration)'
      versioningScheme: byPrereleaseNumber
      majorVersion: '0'
      minorVersion: '1'
      patchVersion: '0'