queue: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: src/Blazor.Extensions.Logging.JS
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 3.0.100-preview-010184'
    inputs:
      version: '3.0.100-preview-010184'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: 'src/Blazor.Extensions.Logging/*.csproj'
      configuration: '$(buildConfiguration)'
      versioningScheme: byPrereleaseNumber
      majorVersion: '0'
      minorVersion: '1'
      patchVersion: '0'


      